@startuml sequence_failure

title Saga - Ошибочные сценарии

skinparam participant<<service>> {
  BackgroundColor #1976D2
  BorderColor #1976D2
  FontColor White
}
hide <<service>> stereotype

actor "Покупатель" as Buyer
participant "API Gateway" as GW <<service>>
participant "Order Service" as Order <<service>>
participant "Inventory Service" as Inventory <<service>>
participant "Payment Service" as Payment <<service>>
participant "Delivery Service" as Delivery <<service>>
participant "Notification Service" as Notify <<service>>
participant "Платёжный шлюз" as PayGW
participant "Служба доставки" as Logistics
actor "Продавец" as Seller

== Ошибка резервирования ==
Buyer -> GW : HTTPS
GW -> Order : REST
Order -> Order : Создать заказ\n(Ожидает оплаты)
Order -> Inventory : OrderPlaced [kafka]
Inventory -> Inventory : Резерв неудачен\n(нет остатка)
Inventory -> Order : InventoryReservationFailed [kafka]
Order -> Order : Отменить заказ
Order -> Notify : OrderCancelled [kafka]
Order -> Inventory : OrderCancelled [kafka]
Notify -> Buyer : Заказ отменён

== Ошибка оплаты ==
Buyer -> GW : HTTPS
GW -> Order : REST
Order -> Inventory : OrderPlaced [kafka]
Inventory -> Inventory : Зарезервировать товары()
Inventory -> Payment : InventoryReserved [kafka]
Inventory -> Order : InventoryReserved [kafka]
Payment -> PayGW : Списание
PayGW --> Payment : Отклонено
Payment -> Order : PaymentFailed [kafka]
Order -> Order : Отменить заказ
Order -> Notify : OrderCancelled [kafka]
Order -> Inventory : OrderCancelled [kafka]
Inventory -> Inventory : Снять резерв()
Inventory -> Order : InventoryReleased [kafka]
Notify -> Buyer : Оплата не прошла

== Ошибка доставки (после оплаты) ==
Buyer -> GW : HTTPS
GW -> Order : REST
Order -> Inventory : OrderPlaced [kafka]
Inventory -> Payment : InventoryReserved [kafka]
Inventory -> Order : InventoryReserved [kafka]
Payment -> PayGW : Списание
PayGW --> Payment : OK
Payment -> Delivery : PaymentSucceeded [kafka]
Payment -> Order : PaymentSucceeded [kafka]
Payment -> Notify : PaymentSucceeded [kafka]
Notify -> Seller : Новый заказ
Delivery -> Logistics : Создание отправки
Logistics --> Delivery : Ошибка
Delivery -> Order : DeliveryRequestFailed [kafka]
Order -> Order : Отменить заказ
Order -> Notify : OrderCancelled [kafka]
Order -> Inventory : OrderCancelled [kafka]
Order -> Payment : DeliveryRequestFailed [kafka]
Payment -> PayGW : Возврат
PayGW --> Payment : OK
Payment -> Order : PaymentRefunded [kafka]
Inventory -> Inventory : Снять резерв()
Inventory -> Order : InventoryReleased [kafka]
Notify -> Buyer : Заказ отменён,\nвозврат средств

@enduml
